#cloud-config
repo_update: true
repo_upgrade: all

packages:
  - pygpgme
  - yum-utils

write_files:
  - content: |
      [Service]
      LimitNOFILE=80000
      LimitNPROC=80000
    path: /etc/systemd/system/tyk-sink.service.d/limits.conf
    owner: root:root
    permissions: '0664'
  - content: |
      ${redis_host != "" ? "TYK_MDCB_STORAGE_HOST=\"${redis_host}\"" : ""}
      ${redis_port != "" ? "TYK_MDCB_STORAGE_PORT=\"${redis_port}\"" : ""}
      ${redis_password != "" ? "TYK_MDCB_STORAGE_PASSWORD=\"${redis_password}\"" : ""}
      ${redis_enable_cluster != "" ? "TYK_MDCB_STORAGE_ENABLECLUSTER=\"${redis_enable_cluster}\"" : ""}
      ${redis_hosts != "" ? "TYK_MDCB_STORAGE_HOSTS=\"${redis_hosts}\"" : ""}
      ${mongo_url != "" ? "TYK_MDCB_ANALYTICSCONFIG_MONGOURL=\"${mongo_url}\"" : ""}
      ${mongo_use_ssl != "" ? "TYK_MDCB_ANALYTICSCONFIG_MONGOUSESSL=\"${mongo_use_ssl}\"" : ""}
      ${forward_to_pump != "" ? "TYK_MDCB_FORWARDANALYTICSTOPUMP=\"${forward_to_pump}\"" : ""}
      ${license_key != "" ? "TYK_MDCB_LICENSE=\"${license_key}\"" : ""}
    path: /etc/default/tyk-sink
    owner: root:root
    permissions: '0660'
  - content: ${custom_config}
    encoding: b64
    path: /run/tyk_sink.conf
    owner: tyk:tyk
    permissions: '0660'

runcmd:
  - export UNIQUE_ID=`hostname -f` && curl -L "https://${token}:@packagecloud.io/install/repositories/tyk/${repository}/config_file.repo?os=el&dist=7&name=$UNIQUE_ID" -o /etc/yum.repos.d/tyk_${repository}.repo
  - [ yum, update ]
  - [ yum, install, -y, tyk-sink-${mdcb_version}-1 ]
  - [ sh, -c, "[ -s /run/tyk_sink.conf ] || cp /run/tyk_sink.conf /opt/tyk-sink/" ]
  - [ systemctl, daemon-reload ]
  - [ systemctl, start, tyk-sink ]
  - [ systemctl, enable, tyk-sink ]
